language: csharp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential clang wget unzip mono-devel
before_script:
  - wget -O /tmp/premake-dev-linux.zip http://sourceforge.net/projects/premake/files/Premake/nightlies/premake-dev-linux.zip/download
  - unzip /tmp/premake-dev-linux.zip
  - export PATH=$PATH:$PWD/bin/release
script:
  - premake5 --cc=clang --arch=x64 gmake
  # Circumvent https://bitbucket.org/premake/premake-dev/issue/258/response-file-doesnt-work-on-linux
  - sed -i '/\@echo/,/\.cs/ { s/\\/\//g; }' build/ENet.make build/ENetDemo.make
  - make -C build/
