language: csharp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential clang wget unzip mono-devel
before_script:
  - wget -O /tmp/premake-dev-linux.zip http://kent.dl.sourceforge.net/project/premake/Premake/nightlies/premake-dev-linux.zip
  - ls -l /tmp/premake-dev-linux.zip
  - file /tmp/premake-dev-linux.zip
  - unzip /tmp/premake-dev-linux.zip
  - export PATH=$PATH:$PWD/bin/release
script:
  - premake5 --cc=clang --arch=x64 gmake
  # Circumvent https://bitbucket.org/premake/premake-dev/issue/258/response-file-doesnt-work-on-linux
  - sed -i '/\@echo/,/\.cs/ { s/\\/\//g; }' build/ENet.make build/ENetDemo.make
  - make -C build/ verbose=1

after_script:
  - cd build/lib/Release-x64
  - tar cjf enetcs-linux-x64.tar.bz2 ENet.dll libenet.so
  - cd ../..
deploy:
  provider: releases
  api_key:
    secure: "ekZ4NhTGNhqh+romed8ONUqGW4KJcH3FFFYa2OgTPd3paPWbuuPma3Aw3xZvx4zAFk8iWImi7zxvNM51OZ3eohKSAUPfxfjlTuPXDvJ6I09nWeUutnKYe7lW5wXUXk0DJR5b/0wXCw9GiPZT/fKPFMa7isvY6C8D+qOjdYGJ19s="
  file: "build/lib/Release-x64/enetcs-linux-x64.tar.bz2"
  title: "enetcs-$TRAVIS_TAG"
  draft: true
  skip_cleanup: true
  on:
    tags: true
