version: 1.0.{build}
branches:
  only:
  - master
configuration:
  - Debug
  - Release
environment:
  matrix:
  - VS_VERSION: vs2012
  - VS_VERSION: vs2013
install:
  - cinst wget
  - wget -nv -O premake.zip http://sourceforge.net/projects/premake/files/Premake/nightlies/premake-dev-windows.zip/download
  - unzip premake.zip
  - move bin\release\premake5.exe .
before_build:
  - git submodule init
  - git submodule update
  - del /F /S build
  - premake5.exe %VS_VERSION%
  - dir
  - dir build\%VS_VERSION%
  - tree
build:
  project: build\$(VS_VERSION)\enet-cs.sln
  verbosity: normal
after_build:
  - tree
artifacts:
  - path: build\$(VS_VERSION)\lib
    name: enetcs-$(configuration)-$(VS_VERSION)
    type: zip
  - path: build\$(VS_VERSION)\bin
    name: ENetDemo-$(configuration)-$(VS_VERSION)
    type: zip
